name: 📅 Create Biweekly Sprint Milestone

on:
  schedule:
    - cron: '0 0 */14 * *'  # Every 14 days at midnight UTC
  workflow_dispatch:        # Allow manual trigger

jobs:
  create-sprint:
    runs-on: ubuntu-latest

    steps:
      - name: Create Sprint Milestone
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const today = new Date();
            const start = today.toISOString().slice(0, 10);
            const endDate = new Date(today.getTime() + 13 * 24 * 60 * 60 * 1000); // 2 weeks from today
            const end = endDate.toISOString().slice(0, 10);
            const sprintTitle = `Sprint - ${start} to ${end}`;

            const { data: existingMilestones } = await github.rest.issues.listMilestones({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            const alreadyExists = existingMilestones.some(m => m.title === sprintTitle);
            if (alreadyExists) {
              console.log("Milestone already exists:", sprintTitle);
            } else {
              await github.rest.issues.createMilestone({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: sprintTitle,
                description: `Sprint planned from ${start} to ${end}`,
                due_on: endDate.toISOString()
              });
              console.log("Milestone created:", sprintTitle);
            }
